Add public for ->writeToDisk() as option
spatie/laravel-sitemap pull request #534
Opened 2024-01-16 15:41 UTC by bmckay959

I'm using S3 for hosting my sitemaps(Using Vapor for the site so local disk isn't an option).

I'm currently generating the sitemap and after creation, I'm then changing the visibility to public. This could cause, though rare, a race condition of me creating the sitemap and before making it public, a search engine crawler would receive a "Access Denied" error from S3.

By adding the visibility option as seen here(https://laravel.com/docs/10.x/filesystem#file-visibility), it resolves this issue.

2024-01-17 08:07 UTC, freekmurze requested changes
Could you add tests and docs for this change?

2024-01-17 08:07 UTC, freekmurze commented on src/Sitemap.php
> +        if($public) {
Could you refactor this to a ternary?

2024-01-18 23:32 UTC, bmckay959 commented
I made the if statements ternary....I'm trying to work through the testing here. `Storage::fake()` uses local storage from what I can tell, which makes the `Storage::getVisibility()` return `League\Flysystem\UnableToRetrieveMetadata: Unable to retrieve the visibility for file at location: sitemap.xml` since it's not utilizing the aws driver. I'll try to look into it more tomorrow/over the weekend when I get time.

2024-01-18 23:33 UTC, bmckay959 commented
Just so you can see what I tried:

```php
it('can write a sitemap to a storage disk and make visibility be public', function () {
    Storage::fake('s3');
    $this->index->writeToDisk('s3', 'sitemap.xml', true);

    $visibility = Storage::getVisibility('sitemap.xml');

    assertMatchesXmlSnapshot(Storage::disk('s3')->get('sitemap.xml'));
    expect($visibility)->toBe('public');
});
```

2024-01-24 07:36 UTC, merged

2024-01-24 07:36 UTC, freekmurze commented
Thank you!

2024-02-08 11:15 UTC, ismaail commented
google search console was giving error `Sitemap could not be read` because the